### ISSUE TITLE
Tugas OOP (Nurul)

### ISSUE THREAD

**Issue by Vespri** [taufik230301/alpro_bootcamp_calssico#45]
Buatlah game Pemain Bola, dengan properti nama, health, stamina dan nama klub. tiap tiap pemain memiliki beberapa method Yaitu : Tendang, Istirahat, Sundulan, Cedera.
1. Jika Pemain Menedang maka stamina dari pemain tersebut berkurang 5.
2. Jika Pemain bersitirahat maka health dan stamina permain tersebut bertambah 20.
3. Jika Pemain menyudul, maka heatlh berkurang 10.
4. Jika Pemain Cedera maka stamina dan health berkurang 5.

**Comment by nurulzzh3101** [comment]
Ada 2 file jawaban tugas OOP

**Comment by Vespri** [comment]
done
